customers = [
  { firstName: 'Juni', lastName: 'Fosser', city: 'Setermoen', country: 'Norway', balance: -86721 },
  {
    firstName: 'Victoria',
    lastName: 'Carr',
    city: 'Queanbeyan',
    country: 'Australia',
    balance: -15574,
  },
  {
    firstName: 'Maddison',
    lastName: 'Obrien',
    city: 'Oxford',
    country: 'United Kingdom',
    balance: -23342,
  },
  {
    firstName: 'Ottilie',
    lastName: 'Weise',
    city: 'Aken (Elbe)',
    country: 'Germany',
    balance: -3379,
  },
  {
    firstName: 'Matias',
    lastName: 'Rautio',
    city: 'Kannonkoski',
    country: 'Finland',
    balance: -29402,
  },
  { firstName: 'Jenny', lastName: 'Smythe', city: 'Killarney', country: 'Ireland', balance: 64258 },
  {
    firstName: 'Marie',
    lastName: 'Pearson',
    city: 'Celbridge',
    country: 'Ireland',
    balance: 33056,
  },
  { firstName: 'Emilia', lastName: 'Kangas', city: 'Nurmes', country: 'Finland', balance: -2409 },
  { firstName: 'Adolfo', lastName: 'Crespo', city: 'Lugo', country: 'Spain', balance: -74237 },
  {
    firstName: 'Phoebe',
    lastName: 'Bailey',
    city: 'Ashbourne',
    country: 'Ireland',
    balance: -60762,
  },
  { firstName: 'Okan', lastName: 'Fahri', city: 'Çanakkale', country: 'Turkey', balance: 556 },
  {
    firstName: 'Steve',
    lastName: 'Leclercq',
    city: 'Plasselb',
    country: 'Switzerland',
    balance: 8326,
  },
  {
    firstName: 'Amanda',
    lastName: 'Tucker',
    city: 'Murrieta',
    country: 'United States',
    balance: -6176,
  },
  { firstName: 'Erik', lastName: 'Mies', city: 'Bad Driburg', country: 'Germany', balance: 71588 },
  {
    firstName: 'Matilda',
    lastName: 'Turner',
    city: 'Whanganui',
    country: 'New Zealand',
    balance: 30519,
  },
  {
    firstName: 'Chad',
    lastName: 'Spencer',
    city: 'Wakefield',
    country: 'United Kingdom',
    balance: -67334,
  },
  {
    firstName: 'Dustin',
    lastName: 'Lambert',
    city: 'Clarksville',
    country: 'United States',
    balance: 89186,
  },
  { firstName: 'Eetu', lastName: 'Tervo', city: 'Viitasaari', country: 'Finland', balance: -20978 },
  { firstName: 'Justine', lastName: 'Scott', city: 'Hampton', country: 'Canada', balance: 87492 },
  { firstName: 'Antonino', lastName: 'Melo', city: 'Uberaba', country: 'Brazil', balance: 44062 },
  { firstName: 'Elisa', lastName: 'Vargas', city: 'Orihuela', country: 'Spain', balance: 57948 },
  { firstName: 'Monica', lastName: 'Ramos', city: 'Oviedo', country: 'Spain', balance: 10287 },
  {
    firstName: 'Mohamed',
    lastName: 'Leon',
    city: 'San Sebastián de Los Reyes',
    country: 'Spain',
    balance: -80559,
  },
  {
    firstName: 'Lawrence',
    lastName: 'Pearson',
    city: 'Celbridge',
    country: 'Ireland',
    balance: 85001,
  },
  {
    firstName: 'Malik',
    lastName: 'Pelletier',
    city: 'Hampstead',
    country: 'Canada',
    balance: 57923,
  },
  {
    firstName: 'Runar',
    lastName: 'Heggernes',
    city: 'Kabelvåg',
    country: 'Norway',
    balance: -926,
  },
  {
    firstName: 'Vida',
    lastName: 'Krogstad',
    city: 'Søre Øyane',
    country: 'Norway',
    balance: -2656,
  },
  {
    firstName: 'Jesse',
    lastName: 'Sippola',
    city: 'Eurajoki',
    country: 'Finland',
    balance: -14448,
  },
  {
    firstName: 'Nicole',
    lastName: 'Hart',
    city: 'Enniscorthy',
    country: 'Ireland',
    balance: -98577,
  },
  { firstName: 'Aronas', lastName: 'Idris', city: 'Høllen', country: 'Norway', balance: -36233 },
  { firstName: 'Milja', lastName: 'Heikkinen', city: 'Tornio', country: 'Finland', balance: 90781 },
  {
    firstName: 'Alfons',
    lastName: 'Schlegel',
    city: 'Rockenhausen',
    country: 'Germany',
    balance: -8003,
  },
  { firstName: 'Nellie', lastName: 'Schjerven', city: 'Rotnes', country: 'Norway', balance: 1171 },
  { firstName: 'William', lastName: 'Larsen', city: 'Nr Åby', country: 'Denmark', balance: -73995 },
  { firstName: 'Ava', lastName: 'Moulin', city: 'Metz', country: 'France', balance: 12927 },
  {
    firstName: 'William',
    lastName: 'Welch',
    city: 'Carrickmacross',
    country: 'Ireland',
    balance: -14360,
  },
  {
    firstName: 'Delores',
    lastName: 'Mitchelle',
    city: 'Boulder',
    country: 'United States',
    balance: -9383,
  },
  { firstName: 'Grace', lastName: 'Boyd', city: 'Dungarvan', country: 'Ireland', balance: 91575 },
  { firstName: 'Lea', lastName: 'Ouellet', city: 'Chelsea', country: 'Canada', balance: -37816 },
  {
    firstName: 'Urs',
    lastName: 'Picard',
    city: 'Walterswil (Be)',
    country: 'Switzerland',
    balance: -60085,
  },
];

module.exports = customers